version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    image: meat/php74
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - default

  #Nginx Service
  webserver:
    build:
      context: .
      dockerfile: Docker/Dockerfile_webserver
    image: meat/nginx
    restart: unless-stopped
    tty: true
    depends_on: 
      - app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default

#Docker Networks
networks:
  default:
    external:
      name: localnetwork